name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Install Auth Service Dependencies
        working-directory: auth-service
        run: npm install

      - name: Install Notification Service Dependencies
        working-directory: notification-service
        run: npm install

      - name: Install Profile Service Dependencies
        working-directory: profile-service
        run: npm install

      - name: Install Recommendation Service Dependencies
        working-directory: recommendation-service
        run: npm install

      - name: Docker Compose Build
        run: docker compose build